name: 'Install Localias'
description: "Install and run localias as a daemon, enabling https domains to be used for CI tests"
author: 'Michael Bianco'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: 'composite'
  steps:

    - name: "Install & Run Localias"
      shell: bash
      run: "${{ github.action_path }}/entrypoint.sh"