name: 'Install Localias'
description: "Install and run localias as a daemon, enabling https domains to be used for CI tests"
author: 'Michael Bianco'

branding:
  icon: 'box'
  color: 'green'

inputs:
  chrome:
    description: 'Warm the chromium database by visiting each host with a headless browser'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:

    - name: "Install & Run Localias"
      shell: bash
      run: "${{ github.action_path }}/entrypoint.sh"
      env:
        WARM_CHROME: ${{ inputs.chrome }}